### PR TITLE
fix: Add missing validation when formatting and mounting block devices

### LINKED ISSUE #391: Creation of raids using partitions resulted in error fstype field is required
Create raids using maas_raid with partitions field resulted in following error:

Terraform resource looks something like this:
resource "maas_raid" "raid" {
  machine   = "<machine id>"
  name        = "md1"
  level          = 1
  partitions = [230, 240] 
}

```
2025-12-09T11:51:04.472+0530 [ERROR] provider.terraform-provider-maas_v2.6.0: Response contains error diagnostic: tf_req_id=81c59fdf-9bb8-33c1-0a43-2950a6980d47 @caller=github.com/hashicorp/terraform-plugin-go@v0.27.0/tfprotov5/internal/diag/diagnostics.go:58 tf_proto_version=5.9 tf_provider_addr=provider tf_resource_type=maas_raid tf_rpc=ApplyResourceChange @module=sdk.proto diagnostic_detail="" diagnostic_severity=ERROR diagnostic_summary="ServerError: 400 Bad Request ({\"fstype\": [\"This field is required.\"]})" timestamp="2025-12-09T11:51:04.472+0530"
2025-12-09T11:51:04.476+0530 [ERROR] vertex "maas_raid.raids[\"pc8a-rb3-n5.md1\"]" error: ServerError: 400 Bad Request ({"fstype": ["This field is required."]})
2025-12-09T11:51:04.947+0530 [ERROR] provider.terraform-provider-maas_v2.6.0: Response contains error diagnostic: @module=sdk.proto diagnostic_detail="" diagnostic_severity=ERROR tf_proto_version=5.9 tf_provider_addr=provider tf_req_id=578587b9-11b2-4454-c6d2-5b51ff7e1e87 tf_resource_type=maas_raid @caller=github.com/hashicorp/terraform-plugin-go@v0.27.0/tfprotov5/internal/diag/diagnostics.go:58 diagnostic_summary="ServerError: 400 Bad Request ({\"fstype\": [\"This field is required.\"]})" tf_rpc=ApplyResourceChange timestamp="2025-12-09T11:51:04.947+0530"
2025-12-09T11:51:04.951+0530 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2025-12-09T11:51:04.951+0530 [ERROR] vertex "maas_raid.raids[\"pc8a-rb3-n5.md2\"]" error: ServerError: 400 Bad Request ({"fstype": ["This field is required."]})
2025-12-09T11:51:04.962+0530 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
```

Note that the raids are created in maas irrespective of this error.
fs_type is an optional argument in maas_raid and hence not provided.

Reapplying the terraform plan again resulted in following error
```
2025-12-09T12:04:27.015+0530 [ERROR] provider.terraform-provider-maas_v2.6.0: Response contains error diagnostic: @module=sdk.proto diagnostic_detail="" diagnostic_severity=ERROR tf_proto_version=5.9 tf_req_id=1a12f940-ba03-aa58-9414-57bbec89dec2 @caller=github.com/hashicorp/terraform-plugin-go@v0.27.0/tfprotov5/internal/diag/diagnostics.go:58 diagnostic_summary="Could not create RAID: ServerError: 400 Bad Request ({\"partitions\": [\"Select a valid choice. 300 is not one of the available choices.\"]})" tf_provider_addr=provider tf_resource_type=maas_raid tf_rpc=ApplyResourceChange timestamp="2025-12-09T12:04:27.015+0530"
2025-12-09T12:04:27.021+0530 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2025-12-09T12:04:27.021+0530 [ERROR] vertex "maas_raid.raids[\"pc8a-rb3-n5.md1\"]" error: Could not create RAID: ServerError: 400 Bad Request ({"partitions": ["Select a valid choice. 300 is not one of the available choices."]})
2025-12-09T12:04:27.489+0530 [ERROR] provider.terraform-provider-maas_v2.6.0: Response contains error diagnostic: @caller=github.com/hashicorp/terraform-plugin-go@v0.27.0/tfprotov5/internal/diag/diagnostics.go:58 @module=sdk.proto tf_provider_addr=provider tf_req_id=9feed40b-ee6e-ab64-e019-5279c5bf0fcc tf_rpc=ApplyResourceChange diagnostic_detail="" diagnostic_severity=ERROR diagnostic_summary="Could not create RAID: ServerError: 400 Bad Request ({\"partitions\": [\"Select a valid choice. 302 is not one of the available choices.\"]})" tf_proto_version=5.9 tf_resource_type=maas_raid timestamp="2025-12-09T12:04:27.489+0530"
2025-12-09T12:04:27.494+0530 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2025-12-09T12:04:27.494+0530 [ERROR] vertex "maas_raid.raids[\"pc8a-rb3-n5.md2\"]" error: Could not create RAID: ServerError: 400 Bad Request ({"partitions": ["Select a valid choice. 302 is not one of the available choices."]})
2025-12-09T12:04:27.504+0530 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
```

### PR DESCRIPTION
**Pull request by andylshort**
## Description of changes

Added validation in the case of `mount_point` being specified, but the `fs_type` not being. Better provided error messages are included to. Acceptance tests are provided to reinforce this behavior. Validation is done in a "fail fast" fashion to keep MAAS and Terraform in sync.

## Issue or ticket link (if applicable)

Resolves #391, #392

## Checklist

- [x] I have written a PR title that follows the advice in CONTRIBUTING.md
- [x] I have written a description of the changes in the PR that is clear and concise.
- [x] I have updated the documentation to reflect the changes.
- [x] I have added or updated the tests to reflect the changes.
- [x] I have run the unit tests and they pass.
- [X] I have run the acceptance tests and they pass.

### CODE REVIEW

File: maas/resource_maas_raid.go [hunk 1]
```diff
@@ -98,6 +98,14 @@ func resourceMAASRAID() *schema.Resource {
 func resourceRAIDCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
 	client := meta.(*ClientConfig).Client
 
+	// Validate the file system and mounting information before attempting to create the logical volume
```
Comment (skatsaounis) [inline maas/resource_maas_raid.go]:
```suggestion
	// Validate the file system and mounting information before attempting to create the RAID
```

**Review by skatsaounis — CHANGES_REQUESTED** [review]
The PR looks good. I found a small typo but apart from that nothing else. Let's fix it and also run the CI tests to confirm that the new acceptance tests are passing. Excellent job!

**Review by skatsaounis — APPROVED** [review]
